---
- name: Create logical volumes and filesystems
  hosts: all
  become: yes
  vars:
    datavg: datavg
    logvg: logvg
    rootvg: rootvg
    mongodblv: mongodblv
    datalv: datalv
    datajournallv: datajournallv
    datatmplv: datatmplv
    db1lv: db1lv
    loglv: loglv
    mongod_user: mongod
    mongod_group: mongod
    mongod_user_ulimit: "nofile 64000"
    mongod_group_ulimit: "nofile 64000"
    swappiness: 1
  tasks:

  #Create all Logical Volumes
  - name: Create logical volume on rootvg called mongodblv
    lvg: 
      vg: "{{ rootvg }}" 
      lv: "{{ mongodblv }}"
      size: 10G
  - name: Create logical volume on datavg called datalv
    lvg: 
      vg: "{{ datavg }}" 
      lv: "{{ datalv }}"
      size: 10G
  - name: Create logical volume on datavg called datajournallv
    lvg: 
      vg: "{{ datavg }}" 
      lv: "{{ datajournallv }}"
      size: 10G
  - name: Create logical volume on datavg called datatmplv
    lvg: 
      vg: "{{ datavg }}" 
      lv: "{{ datatmplv }}"
      size: 15G
  - name: Create logical volume on datavg called db1lv
    lvg: 
      vg: "{{ datavg }}" 
      lv: "{{ db1lv }}"
      size: 20G
  - name: Create logical volume on logvg called loglv
    lvg: 
      vg: "{{ logvg }}" 
      lv: "{{ loglv }}"
      size: 10G


  #Create filesystems and mount them
  - name: Create and mount filesystem /opt/mongodb using mongodblv
    filesystem: 
      fstype: xfs
      dev: /dev/{{ rootvg }}/{{ mongodblv }}
      opts: "-m crc=0 -n ftype=1"
    mount:
      path: /opt/mongodb
      src: /dev/{{ rootvg }}/{{ mongodblv }}
      fstype: xfs
      opts: defaults,noatime
  
  - name: Create and mount filesystem /data/mgo using datalv
    filesystem: 
      fstype: xfs
      dev: /dev/{{ datavg }}/{{ datalv }}
      opts: "-m crc=0 -n ftype=1"
    mount:
      path: /data/mgo
      src: /dev/{{ datavg }}/{{ datalv }}
      fstype: xfs
      opts: defaults,noatime
  
  - name: Create and mount filesystem /data/mgo/journal using datajournallv
    filesystem: 
      fstype: xfs
      dev: /dev/{{ datavg }}/{{ datajournallv }}
      opts: "-m crc=0 -n ftype=1"
    mount:
      path: /data/mgo/journal
      src: /dev/{{ datavg }}/{{ datajournallv }}
      fstype: xfs
      opts: defaults,noatime
  
  - name: Create and mount filesystem /data/mgo/tmp using datatmplv
    filesystem: 
      fstype: xfs
      dev: /dev/{{ datavg }}/{{ datatmplv }}
      opts: "-m crc=0 -n ftype=1"
    mount:
      path: /data/mgo/tmp
      src: /dev/{{ datavg }}/{{ datatmplv }}
      fstype: xfs
      opts: defaults,noatime
  
  - name: Create and mount filesystem /data/mgo/db1 using db1lv
    filesystem: 
      fstype: xfs
      dev: /dev/{{ datavg }}/{{ db1lv }}
      opts: "-m crc=0 -n ftype=1"
    mount:
      path: /data/mgo/db1
      src: /dev/{{ datavg }}/{{ db1lv }}
      fstype: xfs
      opts: defaults,noatime

  # Set permission for filesystems for mongodb user
  - name: Change permission of all those filesystem for user and group mongod:mongod
    file:
      path:
        - /opt/mongodb
        - /data/mgo
        - /data/mgo/journal
        - /data/mgo/tmp
        - /data/mgo/db1
        - /log/mgo
      owner: "{{ mongod_user }}"
      group: "{{ mongod_group }}"

  #Set ulimit for Mongodb User    
  - name: Set ulimit for user mongod, all options unlimited and -n 64000 and -u 64000
    lineinfile:
      path: /etc/security/limits.conf
      line: "{{ mongod_user }} soft nofile {{ mongod_user_ulimit }}"
      state: present
    lineinfile:
      path: /etc/security/limits.conf
      line: "{{ mongod_user }} hard nofile {{ mongod_user_ulimit }}"
      state: present
  
  #Disable Access time on data filesystems
  - name: Disable access time updates on /data/mgo/journal, /data/mgo/ and /data/mgo/db1
    mount:
      path:
        - /data/mgo/journal
        - /data/mgo/
        - /data/mgo/db1
      opts: "noatime"

  #Disable transparent HugePages - Performance Issue    
  - name: Disable transparent hugepages
    sysctl:
      name: vm.transparent_hugepage
      value: never

  #Allows to swap only if a out of memory problem happens     
  - name: Set vm.swappiness to 1
    sysctl:
      name: vm.swappiness
      value: "{{ swappiness }}"

  #Update System C Library used by Mongodb
  - name: Update glibc
    yum:
      name: glibc
      state: latest